// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BingoCard: typeof import('./src/domains/bingo/components/BingoCard.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    Fallback: typeof import('./src/components/Fallback.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RoomCard: typeof import('./src/domains/room/components/RoomCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./src/components/Text.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
    UserName: typeof import('./src/domains/user/components/UserName.vue')['default']
  }
}
